import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <Link href="/default-wallet">
          <button className={styles.testButton}>Rainbowkit wallet</button>
        </Link>
        <Link href="/test-wallet">
          <button className={styles.testButton}>Test wallet</button>
        </Link>
        <Link href="/test-stake">
          <button className={styles.testButton}>Test stake</button>
        </Link>
      </main>
    </div>
  );
};

export default Home;
